name: Docs

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - name: get code
        uses: actions/checkout@v1

      - name: build docs
        run: |
          pip install tox
          tox -e docs

      # Runs a set of commands using the runners shell
      - name: publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
