name: Unit Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "2.7", "3.6", "3.7", "3.8", "3.9" ]
    steps:
    - name: Git Clone
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Generate coverage report
      run: |
        pip install -r requirements.txt
        pip install -r test-requirements.txt
        nosetests -v -l DEBUG --logging-level=DEBUG --with-coverage --cover-package=flask_apscheduler
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
